Update poi-ci.yml

diff --git a/.github/workflows/poi-ci.yml b/.github/workflows/poi-ci.yml
--- a/.github/workflows/poi-ci.yml
+++ b/.github/workflows/poi-ci.yml
@@ -29,12 +29,24 @@ jobs:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v2
 
-      # Runs a single command using the runners shell
-      - name: Run a one-line script
-        run: echo Hello, world!
+      - name: Setup .NET
+        uses: actions/setup-dotnet@v1
+        with:
+          dotnet-version: 2.1.x
+        
+      - name: Restore dependencies
+        run: dotnet restore apis/poi/poi.sln
+      
+      - name: Build
+        run: dotnet build --no-restore apis/poi/poi.sln
 
-      # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
-        run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
+      - name: Unit tests
+        run: dotnet test --no-build --verbosity normal -r testresults --logger "trx" apis/poi/poi.sln
+
+      - name: API POI Tests Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()  # run this step even if previous step failed
+        with:
+          name: API POI Tests       # Name of the check run which will be created
+          path: apis/poi/tests/UnitTests/testresults/*.trx,apis/poi/tests/IntegrationTests/testresults/*.trx   #Path to test results
+          reporter: dotnet-trx      #Reporter
